apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  type: NodePort
  sessionAffinity: None
  ports:
  - name: cqlsh
    protocol: TCP
    port: 9042
    targetPort: 9042
    nodePort: 30042