apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
spec:
  #type: LoadBalancer
  selector:
    app: @project.artifactId@
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
spec:
  selector:
    matchLabels:
      app: @project.artifactId@
  replicas: 1
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      containers:
        - name: @project.artifactId@
          image: @docker.registry@/@project.artifactId@:@project.version@
          ports:
            - containerPort: 9090
          env:
            - name: JAVA_OPTS
              value: -server -Xms32m -Xmx32m